# Generated by Django 3.1.4 on 2021-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='contact',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
