# Generated by Django 3.1.4 on 2021-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='born',
            field=models.DateField(null=True),
        ),
    ]
