# Generated by Django 3.1.4 on 2021-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210128_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactmodel',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
